artifact_location: /Users/pavankola/Documents/MLops/mlpipeline-practice/machinelearningpipeline/MLFLOW_TRACKING_URI/0
creation_time: 1749428907912
experiment_id: '0'
last_update_time: 1749428907912
lifecycle_stage: active
name: Default
